version: "3.8"

services:
  api:
    build:
      context: ./packages/api
    volumes:
      - /app/api/node_modules

  database:
    image: postgres:13-alpine
    restart: always
    volumes:
      - ./packages/api/src/database/sql/create-tables.sql:/docker-entrypoint-initdb.d/1-create-tables.sql
      
volumes:
  postgres_data:
    