version: "3.8"

services:
  api:
    volumes:
      - ./packages/api:/app/api
    ports:
      - 3000:3000
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB} 
    command: "npm run start:dev"
  
  database:
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD=${PG_PASS}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_DB=${PG_DB}

volumes:
  postgres_data:
    